# Generated by Django 3.2.1 on 2021-06-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210605_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='total_views',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
