# Generated by Django 3.2.1 on 2021-06-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_authorprofile_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='total_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
