# Generated by Django 3.2.1 on 2021-06-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
